### ISSUE TITLE
获取用户信息失败

### ISSUE THREAD

**Issue by Hybueno09** [ClassmateLin/pxq_ticket#10]
登录后提示获取用户信息失败，多次尝试都这样，还需要什么信息吗？

**Comment by ClassmateLin** [comment]
> 打包后没出现上面问题 出现新的问题，点击运行按钮后，显示提交成功，开始购票流程 然后 预下单失败，不知道哪里问题

退出重新登录。

**Comment by ClassmateLin** [comment]
> {"comments":"Token invalid","mode":0,"result":{},"statusCode":15012010}
> 
> ```
>     开始购票：
>         名称: 【广州】李克勤「弦续」巡回演唱会-广州站
>         场次: 2024-03-30 周六 19:30
>         票档: 380元
>         数量: 1
> ```

你APP登录，挤掉了软件里面的
