### ISSUE TITLE
创建订单失败

### ISSUE THREAD

**Issue by julyc112233** [ClassmateLin/pxq_ticket#3]
抢票中点击运行后会提示：创建订单失败。

日志：

> 创建订单失败, 出了点小问题
> 创建订单返回数据: CreateOrderResult { status_code: 22039998, comments: "出了点小问题", data: None }
> 预下单成功, 开始提交订单
> 预下单返回数据:PreOrderResult { status_code: 200, comments: "成功", data: PreOrderData { price_items: [PriceItem { price_item_name: "票款总额", price_item_val: 288.0, price_item_type: "TICKET_FEE", direction: "INCREASE", price_item_species: "SEAT_PLAN" }], support_deliveries: [SupportDeliverie { name: "EXPRESS" }] } }
> 
>         开始购票：
>             名称: 【广州】【良辰】国风音乐会( 演出阵容：Winky诗/贰婶-蔡翊昇/不才/以冬 )

平台:windows

**Comment by ClassmateLin** [comment]
> 抢票中点击运行后会提示：创建订单失败。
> 
> 日志：
> 
> > 创建订单失败, 出了点小问题
> > 创建订单返回数据: CreateOrderResult { status_code: 22039998, comments: "出了点小问题", data: None }
> > 预下单成功, 开始提交订单
> > 预下单返回数据:PreOrderResult { status_code: 200, comments: "成功", data: PreOrderData { price_items: [PriceItem { price_item_name: "票款总额", price_item_val: 288.0, price_item_type: "TICKET_FEE", direction: "INCREASE", price_item_species: "SEAT_PLAN" }], support_deliveries: [SupportDeliverie { name: "EXPRESS" }] } }
> > ```
> >     开始购票：
> >         名称: 【广州】【良辰】国风音乐会( 演出阵容：Winky诗/贰婶-蔡翊昇/不才/以冬 )
> > ```
> 
> 平台:windows

门票类型不是演唱会的还有问题，等待更新

**Comment by julyc112233** [comment]
谢谢！

**Comment by ClassmateLin** [comment]
> 谢谢！

你选演唱会类型的试试
