### ISSUE TITLE
你好，我购买了鸭屎香柠檬茶(TG群)，但是显示TG连接已过期

### ISSUE THREAD

**Issue by Crjcc** [ClassmateLin/pxq_ticket#7]
你好，我购买了鸭屎香柠檬茶(TG群)，但是显示TG连接已过期，能拉我进群吗？
我的订单号L3O19PPTFJO9D6PU

**Comment by zhouhu949** [comment]
一样啊，购买了却提示过期

**Comment by ClassmateLin** [comment]
> 一样啊，购买了却提示过期

已补

**Comment by ClassmateLin** [comment]
> 你好，我购买了鸭屎香柠檬茶(TG群)，但是显示TG连接已过期，能拉我进群吗？ 我的订单号L3O19PPTFJO9D6PU

已补
