### ISSUE TITLE
不显示人数购票人数

### ISSUE THREAD

**Issue by zz34959** [ClassmateLin/pxq_ticket#9]
没有购票者信息，app里面已经添加上了。

**Comment by ClassmateLin** [comment]
> 没有购票者信息，app里面已经添加上了。

方便的话提供一下access_token， 私发邮箱

**Comment by zz34959** [comment]
> > 没有购票者信息，app里面已经添加上了。
> 
> 方便的话提供一下access_token， 私发邮箱

access_token刷新失败。

**Comment by ClassmateLin** [comment]
> > > 没有购票者信息，app里面已经添加上了。
> > 
> > 
> > 方便的话提供一下access_token， 私发邮箱
> 
> access_token刷新失败。

退出重登
